In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')
from football_scraper import scraper
from wrangler import wrangle_club_data

In [41]:
#scraper('England')
#scraper('Spain')
#scraper('Germany')
#scraper('Italy')
#scraper('FRance')

In [38]:
def season_unique_club(filename,season,all_seasons=False):
    df = pd.read_csv(filename).drop('Unnamed: 0',axis=1)
    if all_seasons:
        unique_team = df['season'].home_team.unique()
        return unique_team
    unique_team = df[df['season']==season].home_team.unique()
    return unique_team

In [75]:
clubs = season_unique_club('Spain_league.csv','18/19')
goal_diff = [get_goal_diff('Spain_league.csv',club,'18/19') for club in clubs]
points = [get_points('Spain_league.csv',club,'18/19') for club in clubs]

In [77]:
x = pd.DataFrame(
    {'clubs':clubs,
    'gd':goal_diff,
    'points':points}
)

In [79]:
x.sort_values('points')

          clubs  gd  points
3     Vallecano -29      32
15       Huesca -22      33
10       Girona -16      37
2    Valladolid -19      41
5         Celta  -9      41
4       Levante  -7      44
14   Villarreal  -3      44
7       Leganes  -6      45
6         Eibar  -4      47
9      Sociedad  -1      50
1        Alaves -11      50
13        Betis  -8      50
17      Espanol  -2      53
18   Ath Bilbao  -4      53
11       Getafe  13      59
16      Sevilla  15      59
19     Valencia  16      61
12  Real Madrid  17      68
8    Ath Madrid  26      76
0     Barcelona  54      87

In [26]:
club = wrangle_club_data(,'Real Madrid')